- hosts: all
  become: yes
  roles:
  - role: etckeeper
  - role: common-utils

- hosts: kolide-fleet-server
  become: yes
  roles:
  - role: docker-io
  - role: mysql-container
  - role: redis-container
  - role: kolide-fleet

- hosts: all
  become: yes
  roles:
  - role: kolide-osquery-launcher
